version: "3.4"

services:
  web:
    image: apis
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "uvicorn main:app --port=8080 --host=0.0.0.0"
    env_file:
      - .env.production
    ports:
      - 8080:8080
    volumes:
      - .:/app
