version: "3.4"

services:
  web:
    image: fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "uvicorn main:app --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
